### PR TITLE
Fix style according to `PEP8`.

### PR DESCRIPTION
**Pull request by MaikuMori**
Some other small changes like proper shebang and class renames.

Basically more whitespace :).

### CODE REVIEW

**Comment by MayeulC** [comment]
Thanks for the pull request, and sorry for the delay.
This should more or less bring your stats to the same linecount as me :)
Edit : Not so much. But who cares, anyway? Thanks for teaching me these guidelines.

**Comment by MayeulC** [comment]
I should have checked this pull request more attentively, it broke something (I reviewed it quickly the other day, but found something which was annoying me, so I didn't merge it back then, but I couldn't recall what it was today).

I will attempt to fix it quickly.

**Comment by MaikuMori** [comment]
Yea those stats are silly. Might have broken something, but I sorta only changed style.

**Comment by MayeulC** [comment]
Fixed it; btw : 

``` Python
self.dpi = [[None, None], [None, None], [None, None], [None,None]]
# and
self.dpi = [[None, None]] * 4
```

Seem to output the same array in the python console. However, due to the way python handles references, it ends up being 4 times ALWAYS EXACTLY the same object in one array. I don't know if you are aware of a way to shorten the code up without triggering this issue?

**Comment by MaikuMori** [comment]
Oh wow, I didn't think of that at all. I guess just keeping it as is, is okey. Not using lists is an option too, but I didn't want to change the code too much. There is also [defaultdict](https://docs.python.org/3/library/collections.html#collections.defaultdict) which maybe could be used instead.

**Comment by MayeulC** [comment]
Thanks for this. This is probably a good alternative to C-style structures, or to arrays of arrays, such as the one I used in this branch : https://github.com/MayeulC/Saitek/tree/new_VID (Which, admittedly, is not very pretty). 
In this case, I think we could use a dict to store capabilities, as well as device and vendor IDs. Or is it too much of a hassle to make it work with three fields?
I must confess that, being primarily a C programmer, I always worry about the overhead of each solution ;)

**Comment by MaikuMori** [comment]
I used to do some C and I still care about performant solutions, I know what you mean. As for overhead, dicts and objects in python start to get messy when there is 10K+ of them up till then I find it best to just enjoy not having to worry about it.

I had some ideas how to restructure the code a bit when I was going trough it. I might have another look this time with more refactoring focus.

**Comment by MayeulC** [comment]
As you wish. But this time, I shall do some proper testing before accepting the pull request :)

**Pull request merged**
